#include "asm_x86_64.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static char *copy(const char *s) { if (!s) s = ""; size_t n = strlen(s); char *p = malloc(n + 1); if (p) memcpy(p, s, n + 1); return p; }
static CTacInstruction ins(CTacOpcode op, const char *r, const char *l, const char *o, const char *q, const char *t) {
  CTacInstruction x = {op, copy(r), copy(l), copy(o), copy(q), copy(t), 0, 1, 1, 1}; return x;
}
int main(void) {
  CTacResult tac = {0}; tac.capacity = 16; tac.items = calloc(tac.capacity, sizeof(*tac.items));
  tac.items[tac.count++] = ins(C_TAC_ALLOC, "x", NULL, NULL, NULL, "صحيح");
  tac.items[tac.count++] = ins(C_TAC_ASSIGN, "x", "8", NULL, NULL, "صحيح");
  tac.items[tac.count++] = ins(C_TAC_BINARY, "t0", "x", ">", "5", "منطقي");
  tac.items[tac.count++] = ins(C_TAC_BRANCH, "L0", "t0", NULL, "L1", "منطقي");
  tac.items[tac.count++] = ins(C_TAC_PRINT, NULL, "\"كبير\"", NULL, NULL, "خيط_رمزي");
  tac.items[tac.count++] = ins(C_TAC_JUMP, "L1", NULL, NULL, NULL, "");
  tac.items[tac.count++] = ins(C_TAC_LABEL, "L0", NULL, NULL, NULL, "");
  tac.items[tac.count++] = ins(C_TAC_PRINT, NULL, "\"صغير\"", NULL, NULL, "خيط_رمزي");
  tac.items[tac.count++] = ins(C_TAC_LABEL, "L1", NULL, NULL, NULL, "");
  CSemanticResult semantic = {0}; semantic.count = 1; semantic.items = calloc(1, sizeof(*semantic.items));
  semantic.items[0].name = copy("x"); semantic.items[0].type = copy("صحيح");
  CAssemblyResult assembly = {0};
  int ok = c_generate_nasm_x86_64(&tac, &semantic, &assembly);
  ok = ok && assembly.text && strstr(assembly.text, "; generated by arabicc C from 3AC") &&
       strstr(assembly.text, "L0:") && strstr(assembly.text, "fmt_str") &&
       strstr(assembly.text, "cmp rax, 0");
  if (!ok) fprintf(stderr, "3AC NASM golden output is incomplete\n%s\n", assembly.text ? assembly.text : "<null>");
  c_assembly_result_free(&assembly); c_tac_result_free(&tac);
  free(semantic.items[0].name); free(semantic.items[0].type); free(semantic.items);
  return ok ? 0 : 1;
}
