#include "asm_x86_64.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static char *copy(const char *s) { if (!s) s = ""; size_t n = strlen(s); char *p = malloc(n + 1); if (p) memcpy(p, s, n + 1); return p; }
static CTacInstruction ins(CTacOpcode op, const char *r, const char *l, const char *o, const char *q, const char *t) {
  CTacInstruction x = {op, copy(r), copy(l), copy(o), copy(q), copy(t), 0, 1, 1, 1}; return x;
}
int main(void) {
  CTacResult tac = {0}; tac.capacity = 16; tac.items = calloc(tac.capacity, sizeof(*tac.items));
  tac.items[tac.count++] = ins(C_TAC_ALLOC, "x", NULL, NULL, NULL, "صحيح");
  tac.items[tac.count++] = ins(C_TAC_ASSIGN, "x", "8", NULL, NULL, "صحيح");
  tac.items[tac.count++] = ins(C_TAC_BINARY, "$t0", "x", ">", "5", "منطقي");
  tac.items[tac.count++] = ins(C_TAC_BRANCH, "L0", "$t0", NULL, "L1", "منطقي");
  tac.items[tac.count++] = ins(C_TAC_PRINT, NULL, "\"كبير\"", NULL, NULL, "خيط_رمزي");
  tac.items[tac.count++] = ins(C_TAC_JUMP, "L1", NULL, NULL, NULL, "");
  tac.items[tac.count++] = ins(C_TAC_LABEL, "L0", NULL, NULL, NULL, "");
  tac.items[tac.count++] = ins(C_TAC_PRINT, NULL, "\"صغير\"", NULL, NULL, "خيط_رمزي");
  tac.items[tac.count++] = ins(C_TAC_LABEL, "L1", NULL, NULL, NULL, "");
  tac.items[tac.count++] = ins(C_TAC_READ, "flag", NULL, NULL, NULL, "منطقي");
  tac.items[tac.count++] = ins(C_TAC_READ, "letter", NULL, NULL, NULL, "حرفي");
  tac.items[tac.count++] = ins(C_TAC_PRINT, NULL, "flag", NULL, NULL, "منطقي");
  tac.items[tac.count++] = ins(C_TAC_PRINT, NULL, "letter", NULL, NULL, "حرفي");
  CSemanticResult semantic = {0}; semantic.count = 3; semantic.items = calloc(3, sizeof(*semantic.items));
  semantic.items[0].name = copy("x"); semantic.items[0].type = copy("صحيح");
  semantic.items[1].name = copy("flag"); semantic.items[1].type = copy("منطقي");
  semantic.items[2].name = copy("letter"); semantic.items[2].type = copy("حرفي");
  CAssemblyResult assembly = {0};
  int ok = c_generate_nasm_x86_64(&tac, &semantic, &assembly);
  ok = ok && assembly.text && strstr(assembly.text, "; generated by arabicc C from 3AC") &&
       strstr(assembly.text, "L0:") && strstr(assembly.text, "fmt_str") &&
       strstr(assembly.text, "cmp rax, 0") &&
       strstr(assembly.text, "fmt_read_bool: db \"%255s\", 0") &&
       strstr(assembly.text, "read_bool_retry_0:") &&
       strstr(assembly.text, "call strcmp") &&
       strstr(assembly.text, "input_bool_true");
  if (!ok) fprintf(stderr, "3AC NASM golden output is incomplete\n%s\n", assembly.text ? assembly.text : "<null>");
  CTacResult empty_tac = {0};
  CSemanticResult empty_semantic = {0};
  CAssemblyResult empty_assembly = {0};
  const int empty_ok = c_generate_nasm_x86_64(&empty_tac, &empty_semantic, &empty_assembly) &&
                       empty_assembly.text && strstr(empty_assembly.text, "main:") &&
                       strstr(empty_assembly.text, "    ret");
  if (!empty_ok) fprintf(stderr, "empty TAC did not produce a valid Assembly entry point\n%s\n",
                         empty_assembly.text ? empty_assembly.text : "<null>");
  ok = ok && empty_ok;
  c_assembly_result_free(&empty_assembly); c_assembly_result_free(&assembly); c_tac_result_free(&tac);
  for (size_t i = 0; i < semantic.count; i++) {
    free(semantic.items[i].name);
    free(semantic.items[i].type);
  }
  free(semantic.items);
  return ok ? 0 : 1;
}
