import 'dart:async';
import 'dart:convert';
import 'dart:io';

Never fail(String message) => throw StateError(message);

void check(bool condition, String message) {
  if (!condition) fail(message);
}

Map<String, dynamic> requestFor(
  String source, {
  String? target,
  bool execute = true,
  String rootPath = '.',
  String? artifactDirectory,
}) {
  final request = <String, dynamic>{
    'protocolVersion': '0.5.0',
    'rootPath': rootPath,
    'sourcePaths': ['main.arb'],
    'sourceTexts': {'main.arb': source},
    'mode': 'project',
    'entryPath': 'main.arb',
    'execute': execute,
  };
  if (target != null) request['target'] = target;
  if (artifactDirectory != null) {
    request['artifactDirectory'] = artifactDirectory;
  }
  return request;
}

Future<(int, Map<String, dynamic>, String)> run(
  String executable,
  Map<String, dynamic> request, {
  Map<String, String>? environment,
}) async {
  final process = await Process.start(executable, [
    '--protocol',
  ], environment: environment);
  process.stdin.writeln(jsonEncode(request));
  await process.stdin.close();
  final stdout = (await process.stdout.transform(utf8.decoder).join()).trim();
  final stderr = await process.stderr.transform(utf8.decoder).join();
  final exitCode = await process.exitCode;
  check(stdout.isNotEmpty, 'compiler returned no JSON: $stderr');
  return (exitCode, jsonDecode(stdout) as Map<String, dynamic>, stderr);
}

class LineReader {
  final List<String> _queue = [];
  final List<Completer<String>> _waiters = [];

  LineReader(Stream<List<int>> stream) {
    stream.transform(utf8.decoder).transform(const LineSplitter()).listen((
      line,
    ) {
      if (_waiters.isNotEmpty) {
        _waiters.removeAt(0).complete(line);
      } else {
        _queue.add(line);
      }
    });
  }

  Future<String> next() {
    if (_queue.isNotEmpty) return Future.value(_queue.removeAt(0));
    final waiter = Completer<String>();
    _waiters.add(waiter);
    return waiter.future;
  }
}

Future<void> main(List<String> args) async {
  check(args.length == 1, 'usage: dart protocol_smoke.dart <arabicc>');
  final executable = args.single;

  final valid = await run(
    executable,
    requestFor('برنامج اختبار؛ متغير س: صحيح؛ { س = 42؛ اطبع(س)؛ }.'),
  );
  check(valid.$1 == 0, valid.$3);
  check(valid.$2['success'] == true, 'valid program should compile');
  check((valid.$2['tokens'] as List).isNotEmpty, 'tokens are missing');
  check((valid.$2['threeAddressCode'] as List).any((item) => (item as String).startsWith('PRINT ')), 'TAC print lowering is missing');
  check((valid.$2['assembly'] as String).contains('generated by arabicc C from 3AC'), 'Assembly did not come from TAC');
  check(
    (valid.$2['syntaxTree'] as Map)['kind'] == 'program',
    'syntax tree kind is wrong',
  );
  check(
    (valid.$2['symbolTable'] as List).first['name'] == 'س',
    'symbol table is wrong',
  );

  // The sourceTexts map is deliberately ordered with a distractor first, and
  // a value contains text that resembles an entryPath property. The compiler
  // must match actual JSON keys rather than the first textual occurrence.
  final reordered = await run(executable, <String, dynamic>{
    'rootPath': 'text "entryPath": "wrong.arb"',
    'sourceTexts': <String, String>{
      'other.arb': 'برنامج مشتت؛ { اطبع(99)؛ }.',
      'main.arb': 'برنامج مختار؛ { اطبع(42)؛ }.',
    },
    'entryPath': 'main.arb',
    'protocolVersion': '0.5.0',
    'sourcePaths': ['other.arb', 'main.arb'],
    'mode': 'project',
    'execute': true,
  });
  check(reordered.$1 == 0 && reordered.$2['success'] == true,
      'reordered source request should compile');
  check(
    listEquals(reordered.$2['executionOutput'], ['42']),
    'compiler selected the wrong sourceTexts entry',
  );

  final power = await run(
    executable,
    requestFor('برنامج قوة؛ { اطبع(2 ^ 3)؛ اطبع(9 ^ 0.5)؛ }.'),
  );
  check(power.$1 == 0, power.$3);
  check(
    listEquals(power.$2['executionOutput'], ['8', '3']),
    'power output changed',
  );

  final read = await run(
    executable,
    requestFor('برنامج قراءة؛ متغير س: صحيح؛ { اقرأ(س)؛ اطبع(س)؛ }.'),
  );
  check(read.$1 != 0, 'read without input should fail');
  check(read.$2['success'] == false, 'read diagnostics missing');
  check(
    (read.$2['diagnostics'] as List).any(
      (item) => (item as Map)['code'] == 'R001',
    ),
    'R001 is missing',
  );

  final readRequest =
      requestFor('برنامج قراءة؛ متغير س: صحيح؛ { اقرأ(س)؛ اطبع(س)؛ }.')
        ..['mode'] = 'active'
        ..['inputValues'] = {'س': '42'};
  final readWithInput = await run(executable, readRequest);
  check(readWithInput.$1 == 0, readWithInput.$3);
  check(
    listEquals(readWithInput.$2['executionOutput'], ['42']),
    'input output changed',
  );

  final analysisRequest = Map<String, dynamic>.from(readRequest)
    ..['execute'] = false;
  final analysis = await run(executable, analysisRequest);
  check(analysis.$1 == 0, analysis.$3);
  check(
    listEquals(analysis.$2['executionOutput'], []),
    'analysis must not execute',
  );

  final interactiveRequest =
      requestFor(
          'برنامج قراءة؛ متغير س: صحيح؛ متغير ص: صحيح؛ '
          '{ اقرأ(س)؛ اقرأ(ص)؛ اطبع(س)؛ اطبع(ص)؛ }.',
        )
        ..['mode'] = 'active'
        ..['inputValues'] = <String, String>{}
        ..['interactive'] = true;
  final session = await Process.start(executable, ['--protocol']);
  final output = LineReader(session.stdout);
  session.stdin.writeln(jsonEncode(interactiveRequest));
  await session.stdin.flush();
  final first = jsonDecode(await output.next()) as Map;
  check(
    mapEquals(first, {'requestType': 'input', 'name': 'س', 'type': 'صحيح'}),
    'first interactive request changed',
  );
  session.stdin.writeln(jsonEncode({'value': '11'}));
  await session.stdin.flush();
  final second = jsonDecode(await output.next()) as Map;
  check(
    mapEquals(second, {'requestType': 'input', 'name': 'ص', 'type': 'صحيح'}),
    'second interactive request changed',
  );
  session.stdin.writeln(jsonEncode({'value': '22'}));
  await session.stdin.flush();
  final finalResponse = jsonDecode(await output.next()) as Map;
  check(
    listEquals(finalResponse['executionOutput'], ['11', '22']),
    'interactive output changed',
  );
  await session.stdin.close();
  check(await session.exitCode == 0, 'interactive process failed');

  final mismatch = await run(
    executable,
    requestFor(
      'برنامج أنواع؛ متغير رقم: صحيح؛ متغير نص: خيط_رمزي؛ { رقم = نص؛ }.',
    ),
  );
  check(
    mismatch.$1 != 0 && mismatch.$2['success'] == false,
    'type mismatch should fail',
  );
  check(
    (mismatch.$2['diagnostics'] as List).any(
      (item) =>
          (item as Map)['phase'] == 'semantic' &&
          (item['message'] as String).contains('عدم توافق نوع الإسناد'),
    ),
    'type mismatch diagnostic is missing',
  );

  final native = await run(
    executable,
    requestFor(
      'برنامج أصلي؛\nمتغير سعر: حقيقي؛\n{ سعر = 2.5؛ }.\n',
      target: 'dart-native',
    ),
  );
  check(
    native.$1 == 0 && native.$2['success'] == true,
    'native program should compile',
  );
  check(
    (native.$2['assembly'] as String).contains('movsd'),
    'native assembly lost movsd',
  );
  check(
    (native.$2['assembly'] as String).contains('fmt_real'),
    'native assembly lost fmt_real',
  );

  final artifactDirectory = await Directory.systemTemp.createTemp(
    'arabicc-protocol-artifact-',
  );
  try {
    final artifact = await run(
      executable,
      requestFor(
        'برنامج artifact؛ { اطبع(7)؛ }.',
        target: 'dart-native',
        rootPath: artifactDirectory.path,
        artifactDirectory:
            '${artifactDirectory.path}${Platform.pathSeparator}.arabic360${Platform.pathSeparator}build',
      ),
    );
    check(
      artifact.$1 == 0 && artifact.$2['success'] == true,
      'artifact build should succeed',
    );
    final artifacts = artifact.$2['artifacts'];
    check(
      artifacts is List && artifacts.length >= 2,
      'artifact paths are missing',
    );
    for (final path in artifacts) {
      check(
        path is String && await File(path).exists(),
        'artifact file was not written: $path',
      );
    }
    final artifactExecutable = (artifacts as List).last as String;
    final execution = await Process.run(artifactExecutable, const []);
    check(
      execution.exitCode == 0,
      'generated artifact failed: ${execution.stderr}',
    );
  } finally {
    await artifactDirectory.delete(recursive: true);
  }

  final invalid = await run(
    executable,
    requestFor('برنامج اختبار؛ متغير س: صحيح؛ { اطبع(مفقود)؛ }.'),
  );
  check(
    invalid.$1 != 0 && invalid.$2['success'] == false,
    'invalid identifier should fail',
  );
  final diagnostic = (invalid.$2['diagnostics'] as List).first as Map;
  check(diagnostic['phase'] == 'semantic', 'wrong diagnostic phase');
  check(
    (diagnostic['span'] as Map)['sourcePath'] == 'main.arb',
    'wrong diagnostic source',
  );

  final syntax = await run(
    executable,
    requestFor('برنامج اختبار؛ متغير س: صحيح؛ { س = ؛ }.'),
  );
  check(
    syntax.$1 != 0 && syntax.$2['success'] == false,
    'syntax error should fail',
  );
  check(
    ((syntax.$2['diagnostics'] as List).first as Map)['phase'] == 'syntax',
    'wrong syntax diagnostic phase',
  );

  final missingToolDirectory = await Directory.systemTemp.createTemp(
    'arabicc-protocol-missing-tool-',
  );
  try {
    final environment = Map<String, String>.from(Platform.environment)
      ..['ACSYS360_TOOLCHAIN_DIR'] = missingToolDirectory.path
      ..['ACSYS360_TOOLCHAIN_ONLY'] = '1';
    final missingTool = await run(
      executable,
      requestFor(
        'برنامج مفقودة؛ { اطبع(8)؛ }.',
        target: 'dart-native',
        rootPath: missingToolDirectory.path,
        artifactDirectory:
            '${missingToolDirectory.path}${Platform.pathSeparator}build',
      ),
      environment: environment,
    );
    check(
      missingTool.$1 != 0 && missingTool.$2['success'] == false,
      'missing tool should fail gracefully',
    );
    final diagnostics = missingTool.$2['diagnostics'];
    check(
      diagnostics is List &&
          diagnostics.any(
            (item) =>
                item is Map &&
                item['code'] == 'A002' &&
                (item['message'] as String).contains('NASM'),
          ),
      'missing tool diagnostic is missing',
    );
  } finally {
    await missingToolDirectory.delete(recursive: true);
  }
}

bool listEquals(Object? actual, List<Object?> expected) =>
    actual is List &&
    actual.length == expected.length &&
    List.generate(
      actual.length,
      (i) => actual[i] == expected[i],
    ).every((value) => value);

bool mapEquals(Map actual, Map expected) =>
    actual.length == expected.length &&
    expected.entries.every((entry) => actual[entry.key] == entry.value);
