#include "asm_x86_64_internal.h"

#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int c_generate_nasm_x86_64(const CAstNode *program,
                           const CSemanticResult *semantic,
                           CAssemblyResult *result)
{
  if (program == NULL || semantic == NULL || result == NULL ||
      program->kind != C_AST_PROGRAM)
    return 0;
  memset(result, 0, sizeof(*result));
  size_t length = 0U;
  size_t capacity = 0U;
  const size_t frame_size = c_asm_frame_size(semantic);
  const size_t read_count = c_asm_read_count(&program->data.program.statements);

  /* Collect string literals for .data section */
  const char **strings = NULL;
  size_t str_count = 0, str_cap = 0;
  const char **real_values = NULL;
  size_t real_count = 0, real_capacity = 0;
  CAsmContext context = {program, NULL, 0U, real_values, real_count};
  size_t text_capacity = 0;
  c_asm_collect_strings(&program->data.program.statements, &strings, &str_count, &str_cap);
  for (size_t i = 0; i < program->data.program.declarations.count; i++)
  {
    const CAstNode *declaration = program->data.program.declarations.items[i];
    if (declaration->kind == C_AST_CONSTANT_DECLARATION)
    {
      c_asm_collect_text_literal(declaration->data.constant.value, &context.text_values,
                           &context.text_count, &text_capacity);
      c_asm_collect_real_literals(declaration->data.constant.value, &real_values,
                            &real_count, &real_capacity);
    }
  }
  for (size_t i = 0; i < program->data.program.statements.count; i++)
  {
    c_asm_collect_text_literal(program->data.program.statements.items[i],
                         &context.text_values, &context.text_count, &text_capacity);
    c_asm_collect_real_literals(program->data.program.statements.items[i],
                          &real_values, &real_count, &real_capacity);
  }

  context.real_values = real_values;
  context.real_count = real_count;

  /* .data section */
  if (!c_asm_append(&result->text, &length, &capacity,
              "; generated by arabicc C\n"
              "default rel\n"
              "global main\n"
              "extern printf\n"
              "extern scanf\n"
              "extern fflush\n"
              "section .data\n"
              "fmt_int: db \"%%ld\", 10, 0\n"
              "fmt_real: db \"%%.15g\", 10, 0\n"
              "fmt_str: db \"%%s\", 10, 0\n"
              "fmt_bool_true: db \"صح\", 10, 0\n"
              "fmt_bool_false: db \"خطأ\", 10, 0\n"
              "fmt_read_int: db \"%%ld\", 0\n"
              "fmt_read_real: db \"%%lf\", 0\n"
              "fmt_read_bool: db \"%%d\", 0\n"
              "fmt_read_char: db \"%%255s\", 0\n"
              "fmt_read_str: db \"%%255s\", 0\n"))
  {
    c_asm_release_literals(&context, strings, real_values);
    c_assembly_result_free(result);
    return 0;
  }
  for (size_t i = 0; i < str_count; i++)
  {
    if (!c_asm_append(&result->text, &length, &capacity, "str%zu: ", i))
    {
      c_asm_release_literals(&context, strings, real_values);
      c_assembly_result_free(result);
      return 0;
    }
    if (!c_asm_emit_nasm_string(&result->text, &length, &capacity, strings[i]))
    {
      c_asm_release_literals(&context, strings, real_values);
      c_assembly_result_free(result);
      return 0;
    }
  }
  for (size_t i = 0; i < real_count; i++)
  {
    char *end = NULL;
    const double value = strtod(real_values[i], &end);
    uint64_t bits = 0;
    memcpy(&bits, &value, sizeof(bits));
    if (end == real_values[i] ||
        !c_asm_append(&result->text, &length, &capacity,
                "real%zu: dq 0x%" PRIx64 "\n", i, bits))
    {
      c_asm_release_literals(&context, strings, real_values);
      c_assembly_result_free(result);
      return 0;
    }
  }
  for (size_t i = 0; i < context.text_count; i++)
  {
    if (!c_asm_append(&result->text, &length, &capacity, "text%zu: ", i) ||
        !c_asm_emit_nasm_string(&result->text, &length, &capacity, context.text_values[i]))
    {
      c_asm_release_literals(&context, strings, real_values);
      c_assembly_result_free(result);
      return 0;
    }
  }
  size_t request_label_index = 0U;
  for (size_t i = 0; i < program->data.program.statements.count; i++)
  {
    const CAstNode *read = program->data.program.statements.items[i];
    if (read->kind != C_AST_READ)
      continue;
    char request_json[1024];
    const char *read_type = c_asm_type_for(semantic, read->data.access.name);
    const int written = snprintf(
        request_json, sizeof(request_json),
        "{\"requestType\":\"input\",\"name\":\"%s\",\"type\":\"%s\"}\n",
        read->data.access.name, read_type ? read_type : "غير معروف");
    if (written < 0 || (size_t)written >= sizeof(request_json) ||
        !c_asm_append(&result->text, &length, &capacity,
                "fmt_input_request%zu: ", request_label_index) ||
        !c_asm_emit_nasm_bytes(&result->text, &length, &capacity, request_json))
    {
      c_asm_release_literals(&context, strings, real_values);
      c_assembly_result_free(result);
      return 0;
    }
    request_label_index++;
  }

  /* .text / main prologue */
  if (!c_asm_emit_prologue(&result->text, &length, &capacity, frame_size,
                           read_count))
  {
    c_asm_release_literals(&context, strings, real_values);
    c_assembly_result_free(result);
    return 0;
  }

  /* Statements */
  if (!c_asm_emit_program_statements(&context, semantic, result, frame_size,
                                        &length, &capacity))
  {
    c_asm_release_literals(&context, strings, real_values);
    return 1;
  }
  c_asm_release_literals(&context, strings, real_values);
  if (!c_asm_emit_epilogue(&result->text, &length, &capacity))
  {
    c_assembly_result_free(result);
    return 0;
  }
  return 1;
}

void c_assembly_result_free(CAssemblyResult *result)
{
  if (result == NULL)
    return;
  free(result->text);
  for (size_t index = 0U; index < result->diagnostic_count; index++)
  {
    free(result->diagnostics[index]);
  }
  free(result->diagnostics);
  free(result->diagnostic_offsets);
  free(result->diagnostic_lines);
  free(result->diagnostic_columns);
  free(result->diagnostic_lengths);
  memset(result, 0, sizeof(*result));
}
