#include "asm_x86_64_internal.h"

#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int c_generate_nasm_x86_64(const CAstNode *program,
                           const CSemanticResult *semantic,
                           CAssemblyResult *result)
{
  if (program == NULL || semantic == NULL || result == NULL ||
      program->kind != C_AST_PROGRAM)
    return 0;
  memset(result, 0, sizeof(*result));
  size_t length = 0U;
  size_t capacity = 0U;
  const size_t frame_size = c_asm_frame_size(semantic);
  const size_t read_count = c_asm_read_count(&program->data.program.statements);

  /* Collect string literals for .data section */
  const char **strings = NULL;
  size_t str_count = 0, str_cap = 0;
  const char **real_values = NULL;
  size_t real_count = 0, real_capacity = 0;
  CAsmContext context = {program, NULL, 0U, real_values, real_count};
  size_t text_capacity = 0;
  c_asm_collect_strings(&program->data.program.statements, &strings, &str_count, &str_cap);
  for (size_t i = 0; i < program->data.program.declarations.count; i++)
  {
    const CAstNode *declaration = program->data.program.declarations.items[i];
    if (declaration->kind == C_AST_CONSTANT_DECLARATION)
    {
      c_asm_collect_text_literal(declaration->data.constant.value, &context.text_values,
                           &context.text_count, &text_capacity);
      c_asm_collect_real_literals(declaration->data.constant.value, &real_values,
                            &real_count, &real_capacity);
    }
  }
  for (size_t i = 0; i < program->data.program.statements.count; i++)
  {
    c_asm_collect_text_literal(program->data.program.statements.items[i],
                         &context.text_values, &context.text_count, &text_capacity);
    c_asm_collect_real_literals(program->data.program.statements.items[i],
                          &real_values, &real_count, &real_capacity);
  }

  context.real_values = real_values;
  context.real_count = real_count;

  /* .data section */
  if (!c_asm_append(&result->text, &length, &capacity,
              "; generated by arabicc C\n"
              "default rel\n"
              "global main\n"
              "extern printf\n"
              "extern scanf\n"
              "extern fflush\n"
              "section .data\n"
              "fmt_int: db \"%%ld\", 10, 0\n"
              "fmt_real: db \"%%.15g\", 10, 0\n"
              "fmt_str: db \"%%s\", 10, 0\n"
              "fmt_bool_true: db \"صح\", 10, 0\n"
              "fmt_bool_false: db \"خطأ\", 10, 0\n"
              "fmt_read_int: db \"%%ld\", 0\n"
              "fmt_read_real: db \"%%lf\", 0\n"
              "fmt_read_bool: db \"%%d\", 0\n"
              "fmt_read_char: db \"%%255s\", 0\n"
              "fmt_read_str: db \"%%255s\", 0\n"))
  {
    free(strings);
    c_assembly_result_free(result);
    return 0;
  }
  for (size_t i = 0; i < str_count; i++)
  {
    if (!c_asm_append(&result->text, &length, &capacity, "str%zu: ", i))
    {
      free(strings);
      c_assembly_result_free(result);
      return 0;
    }
    if (!c_asm_emit_nasm_string(&result->text, &length, &capacity, strings[i]))
    {
      free(strings);
      c_assembly_result_free(result);
      return 0;
    }
  }
  for (size_t i = 0; i < real_count; i++)
  {
    char *end = NULL;
    const double value = strtod(real_values[i], &end);
    uint64_t bits = 0;
    memcpy(&bits, &value, sizeof(bits));
    if (end == real_values[i] ||
        !c_asm_append(&result->text, &length, &capacity,
                "real%zu: dq 0x%" PRIx64 "\n", i, bits))
    {
      free(strings);
      free(real_values);
      c_assembly_result_free(result);
      return 0;
    }
  }
  for (size_t i = 0; i < context.text_count; i++)
  {
    if (!c_asm_append(&result->text, &length, &capacity, "text%zu: ", i) ||
        !c_asm_emit_nasm_string(&result->text, &length, &capacity, context.text_values[i]))
    {
      free(strings);
      free(real_values);
      free(context.text_values);
      context.text_values = NULL;
      context.text_count = 0;
      c_assembly_result_free(result);
      return 0;
    }
  }
  size_t request_label_index = 0U;
  for (size_t i = 0; i < program->data.program.statements.count; i++)
  {
    const CAstNode *read = program->data.program.statements.items[i];
    if (read->kind != C_AST_READ)
      continue;
    char request_json[1024];
    const char *read_type = c_asm_type_for(semantic, read->data.access.name);
    const int written = snprintf(
        request_json, sizeof(request_json),
        "{\"requestType\":\"input\",\"name\":\"%s\",\"type\":\"%s\"}\n",
        read->data.access.name, read_type ? read_type : "غير معروف");
    if (written < 0 || (size_t)written >= sizeof(request_json) ||
        !c_asm_append(&result->text, &length, &capacity,
                "fmt_input_request%zu: ", request_label_index) ||
        !c_asm_emit_nasm_bytes(&result->text, &length, &capacity, request_json))
    {
      free(strings);
      free(real_values);
      free(context.text_values);
      context.text_values = NULL;
      context.text_count = 0;
      c_assembly_result_free(result);
      return 0;
    }
    request_label_index++;
  }

  /* .text / main prologue */
  if (!c_asm_emit_prologue(&result->text, &length, &capacity, frame_size,
                           read_count))
  {
    free(strings);
    c_assembly_result_free(result);
    return 0;
  }

  /* Statements */
  size_t read_index = 0U;
  size_t boolean_print_index = 0U;
  size_t if_label_index = 0U;
  for (size_t index = 0U; index < program->data.program.statements.count; index++)
  {
    const CAstNode *statement = program->data.program.statements.items[index];
    if (statement->kind == C_AST_IF)
    {
      const size_t label = if_label_index++;
      if (!c_asm_emit_expression(&context, statement->data.conditional.condition, semantic,
                           &result->text, &length, &capacity) ||
          !c_asm_append(&result->text, &length, &capacity,
                  "    cmp rax, 0\n    je if_else%zu\n", label) ||
          !c_asm_emit_native_statements(&context, &statement->data.conditional.then_branch,
                                  semantic, &result->text, &length, &capacity,
                                  &if_label_index))
      {
        (void)c_asm_diagnostic_at(result, statement,
                            "تعذر تحويل الفرع الشرطي إلى NASM");
        free(strings);
        return 1;
      }
      if (!c_asm_append(&result->text, &length, &capacity,
                  "    jmp if_done%zu\nif_else%zu:\n", label, label) ||
          !c_asm_emit_native_statements(&context, &statement->data.conditional.else_branch,
                                  semantic, &result->text, &length, &capacity,
                                  &if_label_index) ||
          !c_asm_append(&result->text, &length, &capacity, "if_done%zu:\n", label))
      {
        (void)c_asm_diagnostic_at(result, statement,
                            "تعذر تحويل الفرع الشرطي إلى NASM");
        free(strings);
        return 1;
      }
      continue;
    }
    if (statement->kind == C_AST_ASSIGNMENT)
    {
      const char *target_type = c_asm_type_for(semantic, statement->data.assignment.name);
      const int is_real = target_type && strcmp(target_type, "حقيقي") == 0;
      const int emitted = is_real
                              ? c_asm_emit_real_expression(&context, statement->data.assignment.expression, semantic,
                                                     real_values, real_count, &result->text,
                                                     &length, &capacity)
                              : c_asm_emit_expression(&context, statement->data.assignment.expression, semantic,
                                                &result->text, &length, &capacity);
      if (!emitted)
      {
        (void)c_asm_diagnostic_at(
            result,
            statement,
            "الإسناد صحيح دلالياً: «%s» من النوع «%s»، لكن مولّد NASM "
            "native لا يدعم هذا النوع حالياً؛ الدعم الحالي محصور في "
            "تخزين وتعبيرات integer",
            statement->data.assignment.name,
            c_asm_type_for(semantic, statement->data.assignment.name)
                ? c_asm_type_for(semantic, statement->data.assignment.name)
                : c_asm_assignment_expression_kind(statement->data.assignment.expression));
        free(strings);
        return 1;
      }
      const int slot = c_asm_slot_for(semantic, statement->data.assignment.name);
      if (slot == 0 || !c_asm_append(&result->text, &length, &capacity,
                               is_real ? "    movsd [rbp-%d], xmm0\n"
                                       : "    mov [rbp-%d], rax\n",
                               slot))
      {
        (void)c_asm_diagnostic_at(result, statement,
                            "متغير الإسناد غير موجود في stack layout");
        free(strings);
        return 1;
      }
    }
    else if (statement->kind == C_AST_READ)
    {
      const int slot = c_asm_slot_for(semantic, statement->data.access.name);
      const char *type = c_asm_type_for(semantic, statement->data.access.name);
      if (type == NULL ||
          (strcmp(type, "صحيح") != 0 && strcmp(type, "حقيقي") != 0 &&
           strcmp(type, "منطقي") != 0 && strcmp(type, "حرفي") != 0 &&
           strcmp(type, "خيط_رمزي") != 0))
      {
        (void)c_asm_diagnostic_at(
            result,
            statement,
            "نوع الإدخال native غير مدعوم؛ المتغير «%s» نوعه «%s»",
            statement->data.access.name,
            type ? type : "غير معروف");
        free(strings);
        return 1;
      }
      const int is_text_input =
          strcmp(type, "حرفي") == 0 || strcmp(type, "خيط_رمزي") == 0;
      const int buffer_slot = (int)(frame_size + 32U + read_index * 256U);
      if (slot == 0 || !c_asm_append(&result->text, &length, &capacity,
                               "    lea "
#ifdef _WIN32
                               "rcx"
#else
                               "rdi"
#endif
                               ", [rel fmt_input_request%zu]\n"
                               "    xor eax, eax\n"
                               "    call printf\n"
                               "    xor "
#ifdef _WIN32
                               "ecx"
#else
                               "edi"
#endif
                               ", "
#ifdef _WIN32
                               "ecx"
#else
                               "edi"
#endif
                               "\n"
                               "    call fflush\n"
                               "    lea "
#ifdef _WIN32
                               "rdx"
#else
                               "rsi"
#endif
                               ", [rbp-%d]\n"
                               "    lea "
#ifdef _WIN32
                               "rcx"
#else
                               "rdi"
#endif
                               ", [rel %s]\n"
                               "    xor eax, eax\n"
                               "    call scanf\n",
                               read_index,
                               is_text_input ? buffer_slot : slot,
                               strcmp(type, "حقيقي") == 0
                                   ? "fmt_read_real"
                                   : strcmp(type, "منطقي") == 0
                                         ? "fmt_read_bool"
                                         : strcmp(type, "حرفي") == 0
                                               ? "fmt_read_char"
                                               : strcmp(type, "خيط_رمزي") == 0
                                                     ? "fmt_read_str"
                                                     : "fmt_read_int"))
      {
        (void)c_asm_diagnostic_at(result, statement, "تعذر تحويل اقرأ إلى scanf");
        free(strings);
        return 1;
      }
      if (is_text_input &&
          !c_asm_append(&result->text, &length, &capacity,
                  "    lea rax, [rbp-%d]\n"
                  "    mov [rbp-%d], rax\n",
                  buffer_slot, slot))
      {
        (void)c_asm_diagnostic_at(result, statement,
                            "تعذر حفظ الإدخال النصي native");
        free(strings);
        return 1;
      }
      read_index++;
    }
    else if (statement->kind == C_AST_PRINT)
    {
      for (size_t vi = 0; vi < statement->data.print.values.count; vi++)
      {
        const CAstNode *val = statement->data.print.values.items[vi];
        if (!val)
          continue;
        if (c_asm_expression_is_real(val, semantic))
        {
          if (!c_asm_emit_real_expression(&context, val, semantic, real_values, real_count,
                                    &result->text, &length, &capacity) ||
              !c_asm_append(&result->text, &length, &capacity,
                      "    movq "
#ifdef _WIN32
                      "rdx"
#else
                      "rsi"
#endif
                      ", xmm0\n"
                      "    lea "
#ifdef _WIN32
                      "rcx"
#else
                      "rdi"
#endif
                      ", [rel fmt_real]\n"
                      "    mov eax, 1\n"
                      "    call printf\n"))
          {
            (void)c_asm_diagnostic_at(result, statement,
                                "تعذر تحويل طباعة الحقيقي إلى NASM");
            free(strings);
            free(real_values);
            return 1;
          }
          continue;
        }
        if (c_asm_expression_is_boolean(val, semantic))
        {
          const size_t label = boolean_print_index++;
          if (!c_asm_emit_expression(&context, val, semantic, &result->text, &length,
                               &capacity) ||
              !c_asm_append(&result->text, &length, &capacity,
                      "    cmp rax, 0\n"
                      "    jne bool_true%zu\n"
                      "    lea "
#ifdef _WIN32
                      "rcx"
#else
                      "rdi"
#endif
                      ", [rel fmt_bool_false]\n"
                      "    xor eax, eax\n"
                      "    call printf\n"
                      "    jmp bool_done%zu\n"
                      "bool_true%zu:\n"
                      "    lea "
#ifdef _WIN32
                      "rcx"
#else
                      "rdi"
#endif
                      ", [rel fmt_bool_true]\n"
                      "    xor eax, eax\n"
                      "    call printf\n"
                      "bool_done%zu:\n",
                      label, label, label, label))
          {
            (void)c_asm_diagnostic_at(result, statement,
                                "تعذر تحويل طباعة المنطقي إلى NASM");
            free(strings);
            free(real_values);
            return 1;
          }
          continue;
        }
        /* Text values and references → use fmt_str */
        if (c_asm_expression_is_text(val, semantic))
        {
          if (!c_asm_emit_text_expression(&context, val, semantic, &result->text, &length,
                                    &capacity) ||
              !c_asm_append(&result->text, &length, &capacity,
                      "    mov "
#ifdef _WIN32
                      "rdx"
#else
                      "rsi"
#endif
                      ", rax\n"
                      "    lea "
#ifdef _WIN32
                      "rcx"
#else
                      "rdi"
#endif
                      ", [rel fmt_str]\n"
                      "    xor eax, eax\n"
                      "    call printf\n"))
          {
            (void)c_asm_diagnostic_at(result, statement, "تعذر تحويل print string إلى NASM");
            free(strings);
            free(real_values);
            free(context.text_values);
            context.text_values = NULL;
            context.text_count = 0;
            return 1;
          }
        }
        else
        {
          /* Integer / variable / expression → use fmt_int */
          if (!c_asm_emit_expression(&context, val, semantic, &result->text, &length, &capacity) ||
              !c_asm_append(&result->text, &length, &capacity,
                      "    mov "
#ifdef _WIN32
                      "rdx"
#else
                      "rsi"
#endif
                      ", rax\n"
                      "    lea "
#ifdef _WIN32
                      "rcx"
#else
                      "rdi"
#endif
                      ", [rel fmt_int]\n"
                      "    xor eax, eax\n"
                      "    call printf\n"))
          {
            (void)c_asm_diagnostic_at(result, statement, "تعذر تحويل print integer إلى NASM");
            free(strings);
            return 1;
          }
        }
      }
    }
    else if (statement->kind != C_AST_EMPTY)
    {
      (void)c_asm_diagnostic_at(result, statement,
                          "تعليمة غير مدعومة في NASM backend الحالي");
      free(strings);
      return 1;
    }
  }
  free(strings);
  if (!c_asm_emit_epilogue(&result->text, &length, &capacity))
  {
    c_assembly_result_free(result);
    return 0;
  }
  return 1;
}

void c_assembly_result_free(CAssemblyResult *result)
{
  if (result == NULL)
    return;
  free(result->text);
  for (size_t index = 0U; index < result->diagnostic_count; index++)
  {
    free(result->diagnostics[index]);
  }
  free(result->diagnostics);
  free(result->diagnostic_offsets);
  free(result->diagnostic_lines);
  free(result->diagnostic_columns);
  free(result->diagnostic_lengths);
  memset(result, 0, sizeof(*result));
}
